"""Write ``playground/src/runtime/unicode-tables.ts`` from Python's ``unicodedata``.

The browser runtime ports ``gidi.inference.text`` / ``decode``, which use two Unicode properties
JavaScript does not expose: the canonical combining class (``unicodedata.combining``) and
``str.isspace``. Both are tabulated here from the same interpreter that produced the reference
outputs, so the TS port classifies every code point exactly like Python. ``dump_web_parity.py``
dumps the same ranges and the parity runner checks the committed table against them.

    uv run python scripts/gen_runtime_unicode_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "playground" / "src" / "runtime" / "unicode-tables.ts"
MAX_CODE_POINT = 0x10FFFF


def ranges(predicate: Callable[[str], bool]) -> list[int]:
    """Inclusive ``[start, end]`` ranges of the code points where ``predicate`` holds, flat."""
    flat: list[int] = []
    start: int | None = None
    for cp in range(MAX_CODE_POINT + 2):
        hit = cp <= MAX_CODE_POINT and predicate(chr(cp))
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            flat += [start, cp - 1]
            start = None
    return flat


def python_unicode_ranges() -> dict[str, list[int]]:
    return {
        "combining": ranges(lambda ch: unicodedata.combining(ch) != 0),
        "space": ranges(str.isspace),
    }


def _format(name: str, flat: list[int]) -> str:
    pairs = [f"0x{a:X}, 0x{b:X}" for a, b in zip(flat[::2], flat[1::2], strict=True)]
    rows = "".join(f"  {pair},\n" for pair in pairs)
    return f"export const {name}: readonly number[] = [\n{rows}]\n"


def main() -> int:
    tables = python_unicode_ranges()
    text = (
        "// Generated by scripts/gen_runtime_unicode_tables.py from Python "
        f"{sys.version_info.major}.{sys.version_info.minor} unicodedata "
        f"(Unicode {unicodedata.unidata_version}). Do not edit.\n"
        "// Flat inclusive [start, end] code point ranges.\n\n"
        "/** `unicodedata.combining(ch) != 0` */\n"
        + _format("COMBINING_RANGES", tables["combining"])
        + "\n/** `str.isspace()` */\n"
        + _format("SPACE_RANGES", tables["space"])
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(
        f"wrote {OUTPUT.relative_to(ROOT)}: {len(tables['combining']) // 2} combining ranges, "
        f"{len(tables['space']) // 2} space ranges"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
